"""empty message

Revision ID: 49df7ff3f416
Revises: 49a99e1c812e
Create Date: 2019-04-07 18:11:49.388301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49df7ff3f416'
down_revision = '49a99e1c812e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('permission_level', sa.Integer(), nullable=False),
    sa.Column('user_config', sa.Text(), nullable=False),
    sa.Column('address_line1', sa.String(length=100), nullable=False),
    sa.Column('address_line2', sa.String(length=50), nullable=False),
    sa.Column('address_city', sa.String(length=50), nullable=False),
    sa.Column('address_postal_code', sa.String(length=10), nullable=False),
    sa.Column('address_country', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
